language: c

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
  - echo deb http://ceph.com/debian-bobtail/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
  - sudo apt-get update
  - sudo apt-get install librados-dev
  - sudo apt-get install lua5.1
  - sudo apt-get install lua5.1-dev

install:
  - autoreconf -I m4 -ivf
  - ./configure
  - make

script: "exit 0"
